name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Explicitly set permissions for the GITHUB_TOKEN
permissions:
  contents: write # Needed to push changes to the repository
  pull-requests: write # Needed if you want to comment on PRs

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint:check

      - name: Check formatting
        run: npm run format:check
      - name: Build the project
        run: npm run build
      - name: Run tests with coverage
        run: npm run coverage
        continue-on-error: true

      - name: Update coverage badge
        if: matrix.node-version == '20.x' && github.ref == 'refs/heads/main'
        run: |
          # Install bc calculator
          sudo apt-get update && sudo apt-get install -y bc

          # Extract coverage percentage from lcov.info
          if [ -f coverage/lcov.info ]; then
            COVERAGE=$(grep -c '^LH:' coverage/lcov.info || echo 0)
            TOTAL=$(grep -c '^LF:' coverage/lcov.info || echo 1)
            PERCENTAGE=$(echo "scale=1; $COVERAGE * 100 / $TOTAL" | bc -l 2>/dev/null || echo "0")
          else
            PERCENTAGE="0"
          fi

          # Determine badge color
          if (( $(echo "$PERCENTAGE >= 90" | bc -l) )); then
            COLOR="brightgreen"
          elif (( $(echo "$PERCENTAGE >= 80" | bc -l) )); then
            COLOR="green"
          elif (( $(echo "$PERCENTAGE >= 70" | bc -l) )); then
            COLOR="yellow"
          elif (( $(echo "$PERCENTAGE >= 60" | bc -l) )); then
            COLOR="orange"
          else
            COLOR="red"
          fi

          # Update README badge
          sed -i "s|\[coverage-badge\]: https://img.shields.io/badge/test%20coverage-[^-]*-[^]]*|\[coverage-badge\]: https://img.shields.io/badge/test%20coverage-${PERCENTAGE}%25-${COLOR}|g" README.md

          # Check if there are changes to commit
          if ! git diff --quiet README.md; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "chore: update coverage badge to ${PERCENTAGE}%"
            git push
          fi
